#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

This script build Docker images for a CI/CD system.

OPTIONS:
   -h      Show this message
   -n      Image name, is also the folder name of subfolders of docker-images
   -v      Version of images to build
   -i      Software repository IP, where hosting offline softwares
   -k      Public key of this user
EOF
}

IMAGE_NAME=
VERSION=1.0
SOFT_REPO_IP=172.17.42.1
sed 's,/,\\\/,g' ~/.ssh/id_rsa.pub > public_key.tmp
PUBLIC_KEY=$(cat public_key.tmp)
rm public_key.tmp

while getopts “hn:v:i:k:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         n)
             IMAGE_NAME=$OPTARG
             ;;
         v)
             VERSION=$OPTARG
             ;;
         i)
             SOFT_REPO_IP=$OPTARG
             ;;
         k)
             PUBLIC_KEY=$OPTARG
             ;;    
         ?)
             usage
             exit
             ;;
     esac
done
 
sed -r -e "s/\{\{VERSION\}\}/$VERSION/g" $IMAGE_NAME/Dockerfile.template > $IMAGE_NAME/Dockerfile.2
sed -r -e "s/\{\{SOFT_REPO_IP\}\}/$SOFT_REPO_IP/g" $IMAGE_NAME/Dockerfile.2 > $IMAGE_NAME/Dockerfile.1
sed -r -e "s/\{\{PUBLIC_KEY\}\}/$PUBLIC_KEY/g" $IMAGE_NAME/Dockerfile.1 > $IMAGE_NAME/Dockerfile

#cat $IMAGE_NAME/Dockerfile

docker build -t nhantran/$IMAGE_NAME:$VERSION $IMAGE_NAME/
rm -f $IMAGE_NAME/Dockerfile.2
rm -f $IMAGE_NAME/Dockerfile.1
rm -f $IMAGE_NAME/Dockerfile
