#!/bin/bash
REPO_NAME=$1
GIT_SERVER=$(docker inspect cde_gitolite | grep IPAddress | cut -d'"' -f4)
JENKINS_SERVER=$(docker inspect cde_jenkins | grep IPAddress | cut -d'"' -f4)
git clone ssh://git@$GIT_SERVER/gitolite-admin

echo "repo    $REPO_NAME" >> gitolite-admin/conf/gitolite.conf
echo "        RW+             = @all" >> gitolite-admin/conf/gitolite.conf
echo "        option hook.post-receive = notify_jenkin" >> gitolite-admin/conf/gitolite.conf

mkdir -p gitolite-admin/local-code/hooks/repo-specific
cd gitolite-admin/local-code/hooks/repo-specific
touch notify_jenkin
echo "#!/bin/bash" >> notify_jenkin
echo "\n" >> notify_jenkin
echo "/usr/bin/curl 'http://$JENKINS_SERVER:8080/git/notifyCommit?url=ssh://git@$GIT_SERVER/$REPO_NAME'" >> notify_jenkin
chmod u+x notify_jenkin
cd ../../../
git add . && git commit -m 'Configured repo $REPO_NAME' && git push